"""added address to events

Revision ID: 36a792170efe
Revises: a4f31f2ededd
Create Date: 2025-12-18 22:06:07.022985

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36a792170efe'
down_revision: Union[str, None] = 'a4f31f2ededd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    default_address = {
        "formatted_address": "Moscow, Russia",
        "lat": 55.516684,
        "lng": 37.290502,
        "place_id": "51197f918609cf4240597a26eabb11e04b40f00101f901fdfc260000000000c00208"
    }
    json_default = json.dumps(default_address)
    op.add_column(
        'events',
        sa.Column(
            'address',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(f"'{json_default}'::jsonb")
        )
    )
    op.execute(f"UPDATE events SET address = '{json_default}'")
    op.alter_column('events', 'address', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'address')
    # ### end Alembic commands ###
