"""removed host_id from event table

Revision ID: a4f31f2ededd
Revises: c01bbd3f3af4
Create Date: 2025-12-13 03:16:22.537923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f31f2ededd'
down_revision: Union[str, None] = 'c01bbd3f3af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_host_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'host_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('events_host_id_fkey'), 'events', 'users', ['host_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
